# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: get code from repository
      uses: actions/checkout@v3
    - name: set up node environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install required dependencies
      run: npm install

    - name: run linter
      run: npm run lint

    - name: run test scripts
      run: npm test

    - name: build static files
      run: npm run build

    - name: upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
       - name: Download static files artifact
         uses: actions/download-artifact@v3
         with:
           path: ./dist

       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
    
  
